---
- name: Test Instance Connection and install Nginx
  hosts: all
  become: true
  tasks:
    - name: Ensure Nginx is installed
      apt:
        name: nginx
        state: present
        update_cache: true
    
    - name: Start and Enable Nginx
      service:
        name: nginx
        state: started
        enabled: true